version: '3.1'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8001:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./hoplacup:/var/www/html

  db:
    image: mariadb:10.6.4-focal
    command: ['--default-authentication-plugin=mysql_native_password', '--init-file', '/docker-entrypoint-initdb.d/init.sql']
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d  # Montage du dossier mysql contenant le script SQL
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - "3306"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8002:80"
    environment:
      - PMA_ARBITRARY=1
    restart: always
    depends_on:
      - db

volumes:
  db_data:

